export const ADMIN_ROUTE = '/admin'
export const SHOP_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const BASKET_ROUTE = '/cart'
export const PRODUCT_ROUTE = '/product'